name: automatic_version

on:
  pull_request:
    types:
      - closed

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure and Commit
        run: ./.github/scripts/configure_and_commit.sh

      - name: Reintegrate Changes
        run: ./.github/scripts/reintegrate_changes.sh
