name: automatic_version

on:
  pull_request:
    types:
      - closed

jobs:
  version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Check if jq is installed
        run: jq --version

      - name: Make configure_and_commit.sh executable
        run: chmod +x ./.github/scripts/configure_and_commit.sh

      - name: configure_and_commit.sh
        run: ./.github/scripts/configure_and_commit.sh ${{ github.event.action }} ${{ github.repository }}
        id: update_and_reintegrate

      - name: Make reintegrate.sh executable
        run: chmod +x ./.github/scripts/reintegrate.sh

      - name: Reintegrate
        run: ./.github/scripts/reintegrate.sh ${{ github.event.action }} ${{ github.repository }} ${{ secrets.GH_TOKEN }}
